.ONESHELL:

# FIXME: This needs a bit work
#  The path for OrcaSlicer is: ~/Library/Application Support/OrcaSlicer/plugins
shared:
	cargo build --target aarch64-apple-darwin
#	mkdir -p target/debug/shared
#	cd target/debug/shared
##	rm * || echo "nothing to remove"
#	ar -x ../libbambu_farm_client.a
#	gcc -shared *.o -o libbambu_networking.so -lc++
	#gcc -shared *.o -o libbambu_networking.dylib -lc++
#	echo "" | gcc -fPIC -shared -x c -o libBambuSource.so -
#	rm $$HOME/.config/BambuStudio/plugins/*.so || echo "nothing to remove"
#	ln -s $$PWD/libbambu_networking.so $$HOME/.config/BambuStudio/plugins/
#	ln -s $$PWD/libBambuSource.so $$HOME/.config/BambuStudio/plugins/
